# -----------------------------------
# Site Specific BGP Config Parameters
# -----------------------------------
bgp:
  local_as: '64551'

# -------------------------------------------------------------------------------------------------------------------------------
# Tenant Network Parameters
# The Interface indicates the Tenant Network Directly Connected Egress Interface that is later Redistributed Into BGP
# The FW Next Hop is the Outside Interface of the Firwall that the Core Switch Layer will Forward Traffic to reach Tenant network
# The SW Next Hop is the Inside Interface of the Firwall that the Core Switch Layer will Forward Traffic to reach other networks
# --------------------------------------------------------------------------------------------------------------------------------
tenant_networks:
  # --------
  # VRF CORE
  # --------
  - interface: Vlan25
    cidr: 10.224.11.40/29
    vrf: CORE
    description: tenant-nontrusted
    enabled: true
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.11.33

  - interface: Vlan25
    cidr: 10.224.11.40/29
    vrf: CORE
    description: tenant-nontrusted
    enabled: true
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.11.33

transit_inside_networks:
  # --------
  # VRF CORE
  # --------
  - cidr: 10.224.21.32/29
    vrf: CORE
    description: inside-transit-core
    fw_next_hop: 10.224.11.28

  - cidr: 10.224.11.32/29
    vrf: CORE
    description: inside-transit-trusted
    fw_next_hop: 10.224.21.28

  - cidr: 10.224.111.5/32
    vrf: CORE
    description: alnfabsw1-loopback-core
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.11.34

  - cidr: 10.224.111.6/32
    vrf: CORE
    description: alnfabsw2-loopback-core
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.11.35

  - cidr: 10.224.121.5/32
    vrf: CORE
    description: alnfabsw1-loopback-trusted
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.21.34

  - cidr: 10.224.121.6/32
    vrf: CORE
    description: alnfabsw1-loopback-trusted
    fw_next_hop: 10.224.11.28
    sw_next_hop: 10.224.21.35

# -----------------------------------------------------------------------------
# Private Summary Static Routes for Northbound Traffic Fwding Through Firewalls
# -----------------------------------------------------------------------------
private_summary_routes:
  # --------
  # VRF CORE
  # --------
  - name: rfc1918_summary_10/8
    cidr: 10.0.0.0/8
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE
  - name: rfc1918_summary_192.168/16
    cidr: 192.168.0.0/16
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE

  # -----------
  # VRF TRUSTED
  # -----------
  - name: rfc1918_summary_10/8
    cidr: 10.0.0.0/8
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
  - name: rfc1918_summary_192.168/16
    cidr: 192.168.0.0/16
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED

# --------------------------------------------------------------------
# Default Static Route for Northbound Traffic Fwding Through Firewalls
# --------------------------------------------------------------------
default_route:
  # --------
  # VRF CORE
  # --------
  - name: default
    cidr: 0.0.0.0/0
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE

  # -----------
  # VRF TRUSTED
  # -----------
  - name: default
    cidr: 0.0.0.0/0
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
