# -----------------------------------
# Site Specific BGP Config Parameters
# -----------------------------------
bgp:
  local_as: '64556'

# -------------------------------------------------------------------------------------------------------------------------------
# Tenant Network Parameters
# The Interface indicates the Tenant Network Directly Connected Egress Interface that is later Redistributed Into BGP
# The FW Next Hop is the Outside Interface of the Firwall that the Core Switch Layer will Forward Traffic to reach Tenant network
# The SW Next Hop is the Inside Interface of the Firwall that the Core Switch Layer will Forward Traffic to reach other networks
# --------------------------------------------------------------------------------------------------------------------------------
tenant_networks:
  # --------
  # VRF CORE
  # --------
  - transit_interface: GigabitEthernet3/2
    primary_transit_cidr: 10.224.13.30/31
    primary_transit_local_ip_index: 0
    primary_transit_peer_ip_index: 1
    secondary_transit_cidr: 10.224.13.34/31
    secondary_transit_local_ip_index: 0
    secondary_transit_peer_ip_index: 1
    transit_peer_bgp_asn: 64512
    tenant_cidr: 10.10.13.1/32
    trusted: false
    provider: aws
    region: us-east-1
    description: tenant1_nontrusted
    enabled: true
    fw_next_hop: 10.224.13.28
    sw_next_hop: 10.224.13.33

  # -----------
  # VRF TRUSTED
  # -----------
  - transit_interface: GigabitEthernet3/3
    primary_transit_cidr: 10.224.23.32/31
    primary_transit_local_ip_index: 0
    primary_transit_peer_ip_index: 1
    primary_transit_peer_bgp_asn: 64512
    secondary_transit_cidr: 10.224.23.36/31
    secondary_transit_local_ip_index: 0
    secondary_transit_peer_ip_index: 1
    transit_peer_bgp_asn: 64512
    tenant_cidr: 10.10.23.1/32
    trusted: true
    provider: aws
    region: us-east-1
    description: tenant1_trusted
    enabled: true
    fw_next_hop: 10.224.23.28
    sw_next_hop: 10.224.23.33

# -----------------------------------------------------------------------------
# Private Summary Static Routes for Northbound Traffic Fwding Through Firewalls
# -----------------------------------------------------------------------------
private_summary_routes:
  # --------
  # VRF CORE
  # --------
  - name: rfc1918_summary_10/8
    cidr: 10.0.0.0/8
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE
  - name: rfc1918_summary_192.168/16
    cidr: 192.168.0.0/16
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE

  # -----------
  # VRF TRUSTED
  # -----------
  - name: rfc1918_summary_10/8
    cidr: 10.0.0.0/8
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
  - name: rfc1918_summary_192.168/16
    cidr: 192.168.0.0/16
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED

# --------------------------------------------------------------------
# Default Static Route for Northbound Traffic Fwding Through Firewalls
# --------------------------------------------------------------------
default_route:
  # --------
  # VRF CORE
  # --------
  - name: default
    cidr: 0.0.0.0/0
    fw_next_hop: 10.224.11.36
    sw_next_hop: 10.224.11.25
    vrf: CORE

  # -----------
  # VRF TRUSTED
  # -----------
  - name: default
    cidr: 0.0.0.0/0
    fw_next_hop: 10.224.21.36
    vrf: TRUSTED
