bgp:
  local_asn: 64556

tenant_networks:
  # --------
  # VRF CORE
  # --------
  - name: tenant-core
    cidr: 10.10.13.1/32
    next_hop: false
    vrf: CORE
    tag: 1000

  - name: tenant-core
    cidr: 10.10.13.2/32
    next_hop: false
    vrf: CORE
    tag: 1000

  # -----------
  # VRF TRUSTED
  # -----------   
  - name: tenant-trusted
    cidr: 10.10.23.1/32
    next_hop: false
    vrf: TRUSTED
    tag: 2000

  - name: tenant-trusted
    cidr: 10.10.23.2/32
    next_hop: false
    vrf: TRUSTED
    tag: 2000

rfc1918_routes:
  - vrf: CORE
    routes:
    - name: rfc1918_summary_10/8
      cidr: 10.0.0.0/8
      next_hop: 10.224.13.36
    - name: rfc1918_summary_172.16/12
      cidr: 172.16.0.0/12
      next_hop: 10.224.13.36
    - name: rfc1918_summary_192.168/16
      cidr: 172.16.0.0/12
      next_hop: 10.224.13.36
    - name: rfc1918_summary_172.16/12
      cidr: 172.16.0.0/12
      next_hop: 10.224.13.36

default_routes:
  - vrf: CORE
    routes:
    - name: default
      cidr: 0.0.0.0/0
      next_hop: 10.224.13.36
