l3_interfaces:
  alncore1:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.0/31
    host_ip: "1"
    vrf: CORE
    description: alnwan1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet1/1
    cidr: 10.224.21.0/31
    host_ip: "1"
    vrf: TRUSTED
    description: alnwan1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.21.4/31
    host_ip: 5
    vrf: CORE
    description: alnwan2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip: 8
    vrf: CORE
    description: alncore2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip: 8
    vrf: TRUSTED
    description: alncore2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.100.0/31
    host_ip: "0"
    vrf: CORE
    description: mckcore1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/3
    cidr: 10.224.200.0/31 
    host_ip: "0"
    vrf: TRUSTED
    description: mckcore1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/1
    cidr: 10.224.21.10/31
    host_ip: 10
    vrf: TRUSTED
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/1
    cidr: 10.224.21.10/31 
    host_ip: "10"
    vrf: CORE
    description: alnfab1
    enabled: yes
    overlay: no
    ospf: no
    bgp: no
    bgp_type: no
  alncore2:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.2/31
    host_ip: "3"
    vrf: CORE
    description: alnwan1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet1/1
    cidr: 10.224.21.2/31
    host_ip: "3"
    vrf: TRUSTED
    description: alnwan1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.21.6/31
    host_ip: "7"
    vrf: CORE
    description: alnwan2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip: "9"
    vrf: CORE
    description: alncore1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip: "9"
    vrf: TRUSTED
    description: alncore1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.100.2/31
    host_ip: "2"
    vrf: CORE
    description: mckcore2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/3
    cidr: 10.224.200.2/31
    host_ip: "2"
    vrf: TRUSTED
    description: mckcore2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/1
    cidr: 10.224.11.12/31
    host_ip: "12"
    vrf: TRUSTED
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/1
    cidr: 10.224.21.12/31
    host_ip: "12"
    vrf: CORE
    description: alnfab2
    enabled: yes
    overlay: no
    ospf: no
    bgp: no
    bgp_type: no
 