# --------------------------
# Transit VLANs to add to DB
# --------------------------
transit_vlans:
- name: OUTSIDE_TRANSIT_CORE
  vlan: 10

# ---------------------
# L2 Transit Interfaces
# ---------------------
l2_transit_interfaces:
  # --------
  # alncore1
  # --------
  alncore1:
  - name: GigabitEthernet3/1
    description: alnfw1
    mode: access
    vlan: 10
    enabled: True
  # --------
  # alncore2
  # --------
  alncore2:
  - name: GigabitEthernet3/1
    description: alnfw1
    mode: access
    vlan: 10
    enabled: True

  # --------
  # mckcore1
  # --------
  mckcore1:
  - name: GigabitEthernet3/1
    description: mckfw1
    mode: access
    vlan: 10
    enabled: True
  # --------
  # mckcore2
  # --------
  mckcore2:
  - name: GigabitEthernet3/1
    description: mckfw1
    mode: access
    vlan: 10
    enabled: True

  # --------
  # ashcore1
  # --------
  ashcore1:
  - name: GigabitEthernet3/1
    description: ashfw1
    mode: access
    vlan: 10
    enabled: True
  # --------
  # ashcore2
  # --------
  ashcore2:
  - name: GigabitEthernet3/1
    description: ashfw1
    mode: access
    vlan: 10
    enabled: True

# --------------------------------
# L3 Transit & Loopback Interfaces
# --------------------------------
l3_transit_loopback_interfaces:
  # --------
  # alncore1
  # --------
  alncore1:
  - name: Loopback0
    cidr: 10.224.1.3/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.111.3/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Loopback2
    cidr: 10.224.121.3/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/1
    cidr: 10.224.11.0/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/1
    cidr: 10.224.21.0/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet0/2
    cidr: 10.224.11.4/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/1
    cidr: 10.224.21.10/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfab1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true
    
  - name: GigabitEthernet3/2
    cidr: 10.224.100.0/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/3
    cidr: 10.224.200.0/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: Vlan10
    cidr: 10.224.11.24/29
    host_ip_index: 2
    vrf: CORE
    description: alnfw1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  # --------
  # alncore2
  # --------
  alncore2:
  - name: Loopback0
    cidr: 10.224.1.4/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.111.4/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Loopback2
    cidr: 10.224.121.4/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/1
    cidr: 10.224.11.2/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/1
    cidr: 10.224.21.2/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet0/2
    cidr: 10.224.11.6/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip_index: 1
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/2
    cidr: 10.224.21.12/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfab2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/2
    cidr: 10.224.100.2/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/3
    cidr: 10.224.200.2/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: Vlan10
    cidr: 10.224.11.24/29
    host_ip_index: 3
    vrf: CORE
    description: alnfw1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  # --------
  # mckcore1
  # --------
  mckcore1:
  - name: Loopback0
    cidr: 10.224.2.1/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.112.3/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Loopback2
    cidr: 10.224.122.3/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/1
    cidr: 10.224.12.0/31
    host_ip_index: 1
    vrf: CORE
    description: mckwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/1
    cidr: 10.224.22.0/31
    host_ip_index: 1
    vrf: TRUSTED
    description: mckwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet0/2
    cidr: 10.224.12.4/31
    host_ip_index: 1
    vrf: CORE
    description: mckwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/0
    cidr: 10.224.12.8/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/0
    cidr: 10.224.22.8/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/1
    cidr: 10.224.22.10/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckfab1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true
    
  - name: GigabitEthernet3/2
    cidr: 10.224.100.0/31
    host_ip_index: 1
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/3
    cidr: 10.224.200.0/31 
    host_ip_index: 1
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: Vlan10
    cidr: 10.224.12.24/29
    host_ip_index: 2
    vrf: CORE
    description: mckfw1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  # --------
  # mckcore2
  # --------
  mckcore2:
  - name: Loopback0
    cidr: 10.224.2.2/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.112.4/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Loopback2
    cidr: 10.224.122.4/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/1
    cidr: 10.224.12.2/31
    host_ip_index: 1
    vrf: CORE
    description: mckwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/1
    cidr: 10.224.22.2/31
    host_ip_index: 1
    vrf: TRUSTED
    description: mckwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet0/2
    cidr: 10.224.12.6/31
    host_ip_index: 1
    vrf: CORE
    description: mckwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet1/0
    cidr: 10.224.12.8/31
    host_ip_index: 1
    vrf: CORE
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/0
    cidr: 10.224.22.8/31
    host_ip_index: 1
    vrf: TRUSTED
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet2/2
    cidr: 10.224.22.12/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckfab2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/2
    cidr: 10.224.100.2/31
    host_ip_index: 1
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: GigabitEthernet3/3
    cidr: 10.224.200.2/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: true

  - name: Vlan10
    cidr: 10.224.12.24/29
    host_ip_index: 3
    vrf: CORE
    description: mckfw1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

# ----
# VRRP
# ----
vrrp:
  # ---
  # aln
  # ---
  alncore1:
    priority: 200
    host_ip_index: 2 
  alncore2:
    priority: 100
    host_ip_index: 3
  # ---
  # mck
  # ---
  mckcore1:
    priority: 200
    host_ip_index: 2 
  mckcore2:
    priority: 100
    host_ip_index: 3
  # ---
  # ash
  # ---
  ashcore1:
    priority: 200
    host_ip_index: 2 
  ashcore2:
    priority: 100
    host_ip_index: 3

# -----------------------------
# Route Redistribution Into BGP
# -----------------------------
redistribution:
  into_bgp:
    from_connected:
      route_map_entries:
      - vrf: CORE
        name: CONN_BGP_CORE
        sequence: 1000
        action: permit
        match_interfaces:
        - Loopback1

      - vrf: TRUSTED
        name: CONN_BGP_TRUSTED
        sequence: 1000
        action: permit
        match_interfaces: 
        - Loopback2

    from_static:
      route_map_entries:
      - vrf: CORE
        name: STATIC_BGP_CORE
        sequence: 1000
        action: permit
        match_tags:
        - 1000

