l3_interfaces:
  alncore1:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.0/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet1/1
    cidr: 10.224.21.0/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.21.4/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.100.0/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/3
    cidr: 10.224.200.0/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet2/1
    cidr: 10.224.21.10/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfw1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/1
    cidr: 10.224.21.10/31 
    host_ip_index: 0
    vrf: CORE
    description: alnfab1
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    bgp: false
    bgp_type: false
  alncore2:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.2/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet1/1
    cidr: 10.224.21.2/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnwan1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.21.6/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet1/0
    cidr: 10.224.11.8/31
    host_ip_index: 1
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.8/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.100.2/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/3
    cidr: 10.224.200.2/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet2/1
    cidr: 10.224.11.12/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfw1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet3/1
    cidr: 10.224.21.12/31
    host_ip_index: 0
    vrf: CORE
    description: alnfab2
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    bgp: false
    bgp_type: false
 