l3_interfaces:
  alnfab1:
  - name: GigabitEthernet2/1
    cidr: 10.224.21.10/31 
    host_ip_index: 1
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet3/0
    cidr: 10.224.11.14/31 
    host_ip_index: 0
    vrf: CORE
    description: alnfw1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no'
    bgp: 'no'
    bgp_type: 'no'
  - name: GigabitEthernet3/1
    cidr: 10.224.21.14/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfw1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'no'
    bgp_type: 'no'
  - name: GigabitEthernet1/0
    cidr: 10.224.11.18/31
    host_ip_index: 0
    vrf: CORE
    description: alnfab2
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.18/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfab2
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.11.20/31
    host_ip_index: 0
    vrf: CORE
    description: alnnontrust
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'yes'
    bgp_type: external
  - name: GigabitEthernet3/3
    cidr: 10.224.21.20/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alntrust
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'yes'
    bgp_type: external
  alnfab2:
  - name: GigabitEthernet2/1
    cidr: 10.224.21.14/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet3/0
    cidr: 10.224.11.16/31
    host_ip_index: 0
    vrf: CORE
    description: alnfw1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no'
    bgp: 'no'
    bgp_type: 'no'
  - name: GigabitEthernet3/1
    cidr: 10.224.21.16/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alnfw1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'no'
    bgp_type: 'no'
  - name: GigabitEthernet1/0
    cidr: 10.224.11.18/31
    host_ip_index: 1
    vrf: CORE
    description: alnfab1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.18/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnfab1
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'yes'
    bgp: 'yes'
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.11.22/31
    host_ip_index: 0
    vrf: CORE
    description: alnnontrust
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'yes'
    bgp_type: external
  - name: GigabitEthernet3/3
    cidr: 10.224.21.22/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alntrust
    enabled: true
    underlay: 'no'
    physical: 'yes'
    ospf_active: 'no' 
    bgp: 'yes'
    bgp_type: external