l3_interfaces:
  alnfab1:
  - name: GigabitEthernet2/1
    cidr: 10.224.21.10/31 
    host_ip: 11
    vrf: TRUSTED
    description: alncore1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/0
    cidr: 10.224.11.14/31 
    host_ip: 14
    vrf: CORE
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: no
    bgp: no
    bgp_type: no
  - name: GigabitEthernet3/1
    cidr: 10.224.21.14/31
    host_ip: 14
    vrf: TRUSTED
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: no 
    bgp: no
    bgp_type: no
  - name: GigabitEthernet1/0
    cidr: 10.224.11.18/31
    host_ip: 18
    vrf: CORE
    description: alnfab2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.18/31 
    host_ip: 18
    vrf: TRUSTED
    description: alnfab2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.11.20/31
    host_ip: 20
    vrf: CORE
    description: alnnontrust
    enabled: yes
    overlay: no
    ospf: no 
    bgp: yes
    bgp_type: external
  - name: GigabitEthernet3/3
    cidr: 10.224.21.20/31
    host_ip: 20
    vrf: TRUSTED
    description: alntrust
    enabled: yes
    overlay: no
    ospf: no 
    bgp: yes
    bgp_type: external
  alnfab2:
  - name: GigabitEthernet2/1
    cidr: 10.224.21.14/31
    host_ip: 14
    vrf: TRUSTED
    description: alncore2
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/0
    cidr: 10.224.11.18/31
    host_ip: 18
    vrf: CORE
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: no
    bgp: no
    bgp_type: no
  - name: GigabitEthernet3/1
    cidr: 10.224.21.18/31
    host_ip: 18
    vrf: TRUSTED
    description: alnfw1
    enabled: yes
    overlay: no
    ospf: no 
    bgp: no
    bgp_type: no
  - name: GigabitEthernet1/0
    cidr: 10.224.11.18/31
    host_ip: 19
    vrf: CORE
    description: alnfab1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet2/0
    cidr: 10.224.21.18/31
    host_ip: 19
    vrf: TRUSTED
    description: alnfab1
    enabled: yes
    overlay: no
    ospf: yes
    bgp: yes
    bgp_type: internal
  - name: GigabitEthernet3/2
    cidr: 10.224.11.22/31
    host_ip: 22
    vrf: CORE
    description: alnnontrust
    enabled: yes
    overlay: no
    ospf: no 
    bgp: yes
    bgp_type: external
  - name: GigabitEthernet3/3
    cidr: 10.224.21.22/31
    host_ip: 22
    vrf: TRUSTED
    description: alntrust
    enabled: yes
    overlay: no
    ospf: no 
    bgp: yes
    bgp_type: external