l3_interfaces:
  # -------------------------------------------------------
  # alnfw1
  # -------------------------------------------------------
  alnfw1:
  - name: Vlan10
    cidr: 10.224.21.24/29
    host_ip_index: 4
    vrf: CORE
    description: alncore
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_asn }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan15
    cidr: 10.224.11.32/29
    host_ip_index: 4
    vrf: CORE
    description: alnfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_asn }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan20
    cidr: 10.224.21.32/29
    host_ip_index: 4
    vrf: TRUSTED
    description: alnfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_asn }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false
    
