# --------------------------
# Transit VLANs to add to DB
# --------------------------
transit_vlans:
- name: OUTSIDE_TRANSIT_CORE
  vlan: 10
- name: INSIDE_TRANSIT_CORE
  vlan: 15
- name: INSIDE_TRANSIT_TRUSTED
  vlan: 20

# ---------------------
# L2 Transit Interfaces
# ---------------------
l2_transit_interfaces:
  # ---------
  # alnmckfw1
  # ---------
  alnmckfw1:
  - name: GigabitEthernet0/1
    description: alncore1
    mode: access
    vlan: 10
    enabled: true
  - name: GigabitEthernet0/2
    description: mckcore1
    mode: access
    vlan: 10
    enabled: true
  - name: GigabitEthernet1/1
    description: alnfab1
    mode: access
    vlan: 15
    enabled: true
  - name: GigabitEthernet1/2
    description: mckfab2
    mode: access
    vlan: 15
    enabled: true
  - name: GigabitEthernet2/1
    description: alnfab1
    mode: access
    vlan: 20
    enabled: true
  - name: GigabitEthernet2/2
    description: mckfab2
    mode: access
    vlan: 20
    enabled: true

  # ------
  # ashfw1
  # ------
  ashfw1:
  - name: GigabitEthernet0/1
    description: ashcore1
    mode: access
    vlan: 10
    enabled: true
  - name: GigabitEthernet0/2
    description: ashcore2
    mode: access
    vlan: 10
    enabled: true
  - name: GigabitEthernet1/1
    description: ashcld1
    mode: access
    vlan: 15
    enabled: true
  - name: GigabitEthernet1/2
    description: ashcld2
    mode: access
    vlan: 15
    enabled: true
  - name: GigabitEthernet2/1
    description: ashcld1
    mode: access
    vlan: 20
    enabled: true
  - name: GigabitEthernet2/2
    description: ashcld2
    mode: access
    vlan: 20
    enabled: true

# --------------------------------
# L3 Transit & Loopback Interfaces
# --------------------------------
l3_transit_loopback_interfaces:
  # ------
  # alnfw1
  # ------
  alnfw1:
  - name: Vlan10
    cidr: 10.224.11.24/29
    host_ip_index: 4
    vrf: CORE
    description: alncore
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan15
    cidr: 10.224.11.32/29
    host_ip_index: 4
    vrf: CORE
    description: alnfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan20
    cidr: 10.224.21.32/29
    host_ip_index: 4
    vrf: CORE
    description: alnfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false
    
  # ------
  # mckfw1
  # ------
  mckfw1:
  - name: Vlan10
    cidr: 10.224.12.24/29
    host_ip_index: 4
    vrf: CORE
    description: mckcore
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan15
    cidr: 10.224.12.32/29
    host_ip_index: 4
    vrf: CORE
    description: mckfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan20
    cidr: 10.224.22.32/29
    host_ip_index: 4
    vrf: CORE
    description: mckfab
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  # ------
  # ashfw1
  # ------
  ashfw1:
  - name: Vlan10
    cidr: 10.224.13.24/29
    host_ip_index: 4
    vrf: CORE
    description: ashcore
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan15
    cidr: 10.224.13.32/29
    host_ip_index: 4
    vrf: CORE
    description: ashcld
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: Vlan20
    cidr: 10.224.23.32/29
    host_ip_index: 4
    vrf: CORE
    description: ashcld
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false
    