bgp:
  local_asn: 64551

tenant_networks:
  # --------
  # VRF CORE
  # --------
  - name: tenant-core
    cidr: 10.10.12.40/29
    next_hop: 10.224.12.25
    vrf: CORE
    tag: 1000

  # -----------
  # VRF TRUSTED
  # -----------  
  - name: tenant-trusted
    cidr: 10.10.22.40/29
    next_hop: false
    vrf: TRUSTED
    tag: 2000

private_summary_routes:
  - name: rfc1918_summary_10/8
    cidr: 10.0.0.0/8
    fw_next_hop: 10.224.12.36
    vrf: CORE
    tag: 1000
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.12.36
    vrf: CORE
    tag: 1000
  - name: rfc1918_summary_192.168/16
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.12.36
    vrf: CORE
    tag: 1000
  - name: rfc1918_summary_172.16/12
    cidr: 172.16.0.0/12
    fw_next_hop: 10.224.12.36
    vrf: CORE
    tag: 1000

default_route:
  - name: default
    cidr: 0.0.0.0/0
    fw_next_hop: 10.224.12.36
    vrf: CORE
    tag: 1000