bgp:
  local_asn: 64551

tenant_networks:
  - vrf: CORE
    subnets:
    - name: tenant1
      cidr: 10.10.12.1/32
      next_hop: 10.224.12.25
    - name: tenant2
      cidr: 10.10.12.2/32
      next_hop: 10.224.12.25
  - vrf: TRUSTED
    subnets:
    - name: tenant3
      cidr: 10.10.22.1/32
      next_hop: false
    - name: tenant4
      cidr: 10.10.22.2/32
      next_hop: false

rfc1918_routes:
  - vrf: CORE
    routes:
    - name: rfc1918_summary_10/8
      cidr: 10.0.0.0/8
      next_hop: 10.224.12.36
    - name: rfc1918_summary_172.16/12
      cidr: 172.16.0.0/12
      next_hop: 10.224.12.36
    - name: rfc1918_summary_192.168/16
      cidr: 172.16.0.0/12
      next_hop: 10.224.12.36
    - name: rfc1918_summary_172.16/12
      cidr: 172.16.0.0/12
      next_hop: 10.224.12.36

default_routes:
  - vrf: CORE
    routes:
    - name: default
      cidr: 0.0.0.0/0
      next_hop: 10.224.12.36
