l3_interfaces:
  alnnontrust1:
  - name: GigabitEthernet0/0
    cidr: 10.224.11.20/31
    host_ip_index: 1
    vrf: CORE
    description: alnfab1
    enabled: 'yes'
    underlay: 'no'
    physical: 'yes'
    ospf: 'no'
    bgp: 'yes'
    bgp_type: external
  - name: GigabitEthernet0/1
    cidr: 10.224.11.22/31
    host_ip_index: 1
    vrf: CORE
    description: alnfab2
    enabled: 'yes'
    underlay: 'no'
    physical: 'yes'
    ospf: 'no'
    bgp: 'yes'
    bgp_type: external