l3_interfaces:
  alntrust1:
  - name: GigabitEthernet0/0
    cidr: 10.224.21.20/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnfab1
    enabled: True
    underlay: False
    physical: True
    ospf: False
    bgp: True
    bgp_type: external
  - name: GigabitEthernet0/1
    cidr: 10.224.21.22/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnfab2
    enabled: True
    underlay: False
    physical: True
    ospf: False
    bgp: True
    bgp_type: external