l3_interfaces:
  alntrust1:
  - name: Loopback1
    cidr: 10.224.111.7/32
    host_ip_index: 0
    vrf: CORE
    description: loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_type: false
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false
    
  - name: Loopback2
    cidr: 10.224.121.7/32
    host_ip_index: 0
    vrf: TRUSTED
    description: loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_type: false
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false
    
  - name: GigabitEthernet0/0
    cidr: 10.224.21.20/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnfab1
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_type: external
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: false
    
  - name: GigabitEthernet0/1
    cidr: 10.224.21.22/31
    host_ip_index: 1
    vrf: TRUSTED
    description: alnfab2
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_type: external
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: false
    