# --------------------------------
# L3 Transit & Loopback Interfaces
# --------------------------------
l3_transit_loopback_interfaces:
  # -------------------------------------------------------
  # alntrust1
  # -------------------------------------------------------
  ashtrust1:
  - name: Loopback0
    cidr: 10.224.3.8/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback2
    cidr: 10.224.123.8/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/1
    cidr: 10.224.23.32/31
    host_ip_index: 1
    vrf: TRUSTED
    description: ashcld1
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: false

  - name: GigabitEthernet0/2
    cidr: 10.224.23.36/31
    host_ip_index: 1
    vrf: TRUSTED
    description: ashcld2
    enabled: true
    underlay: false
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: false