l3_interfaces:
  alnwan1:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.0/31
    host_ip_index: 0
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/3
    cidr: 10.224.21.0/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.11.2/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/4
    cidr: 10.224.21.2/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/5
    cidr: 10.224.253.0/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan2
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    bgp: false
    bgp_type: false
  - name: Tunnel1
    cidr: 10.224.254.0/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan2
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    bgp: true
    bgp_type: external
  - name: Tunnel2
    cidr: 10.224.255.0/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: ashwan2
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    bgp: true
    bgp_type: external
  alnwan2:
  - name: GigabitEthernet0/1
    cidr: 10.224.11.4/31
    host_ip_index: 0
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/2
    cidr: 10.224.11.6/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    bgp: true
    bgp_type: internal
  - name: GigabitEthernet0/3
    cidr: 10.224.253.2/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan4
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    bgp: false
    bgp_type: false
  - name: Tunnel1
    cidr: 10.224.254.2/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan4
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    bgp: true
    bgp_type: external