
# ----------------------------------------------------------------------------------------------
# Policy that determines how many ASNs to Preprend when Advertising BGP routes to eBGP Neighbors
# ----------------------------------------------------------------------------------------------
ebgp_prepend_route_policy:
# --------
# VRF CORE
# --------
- role: primary
  vrf: CORE
  devices:
  - name: mckwan1
    as_path_prepend: 5
  - name: ashwan1
    as_path_prepend: 5

- role: secondary
  vrf: CORE
  devices:
  - name: alnwan1
    as_path_prepend: 5
  - name: ashwan2
    as_path_prepend: 0

- role: tertiary
  vrf: CORE
  devices:
  - name: ashwan3
    as_path_prepend: 2
  - name: mckwan2
    as_path_prepend: 2

- role: quarternary
  vrf: CORE
  devices:
  - name: ashwan4
    as_path_prepend: 3
  - name: alnwan2
    as_path_prepend: 3

# -----------
# VRF TRUSTED
# -----------
- role: primary
  vrf: TRUSTED
  devices:
  - name: mckwan1
    as_path_prepend: 0
  - name: ashwan1
    as_path_prepend: 0 

- role: secondary
  vrf: TRUSTED
  devices:
  - name: alnwan1
    as_path_prepend: 5
  - name: ashwan2
    as_path_prepend: 0

# --------------------------------
# L3 Transit & Loopback Interfaces
# --------------------------------
l3_transit_loopback_interfaces:
  # -------
  # alnwan1
  # -------
  alnwan1:
  - name: Loopback0
    cidr: 10.224.1.1/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.111.1/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.121.1/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/1
    cidr: 10.224.11.0/31
    host_ip_index: 0
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/3
    cidr: 10.224.21.0/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/2
    cidr: 10.224.11.2/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/4
    cidr: 10.224.21.2/31
    host_ip_index: 0
    vrf: TRUSTED
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/5
    cidr: 10.224.253.0/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan2
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.0/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan2
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.1
    
  - name: Tunnel2
    cidr: 10.224.255.0/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: ashwan2
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.1

  # -------
  # alnwan2
  # -------
  alnwan2:
  - name: Loopback0
    cidr: 10.224.1.2/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.111.2/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.121.2/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/1
    cidr: 10.224.11.4/31
    host_ip_index: 0
    vrf: CORE
    description: alncore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/2
    cidr: 10.224.11.6/31
    host_ip_index: 0
    vrf: CORE
    description: alncore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/3
    cidr: 10.224.253.2/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan4
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.2/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan4
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/3
    tunnel_destination: 10.224.253.3

  # -------
  # ashwan2
  # -------
  ashwan2:
  - name: Loopback1
    cidr: 10.224.113.2/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.123.2/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: GigabitEthernet0/5
    cidr: 10.224.253.0/31
    host_ip_index: 1
    vrf: EDGE
    description: alnwan1
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.0/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.0
    
  - name: Tunnel2
    cidr: 10.224.255.0/31 
    host_ip_index: 1
    vrf: TRUSTED
    description: alnwan4
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.0

  # -------
  # mckwan1
  # -------
  mckwan1:
  - name: Loopback0
    cidr: 10.224.2.1/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.112.1/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.122.1/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/1
    cidr: 10.224.12.0/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/3
    cidr: 10.224.22.0/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/2
    cidr: 10.224.12.2/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/4
    cidr: 10.224.22.2/31
    host_ip_index: 0
    vrf: TRUSTED
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '2'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/5
    cidr: 10.224.253.4/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan1
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.4/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.5
    
  - name: Tunnel2
    cidr: 10.224.255.4/31 
    host_ip_index: 0
    vrf: TRUSTED
    description: ashwan1
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/5
    tunnel_destination: 10.224.253.5

  # -------
  # mckwan2
  # -------
  mckwan2:
  - name: Loopback0
    cidr: 10.224.2.2/32
    host_ip_index: 0
    vrf: GLOBAL
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: 0
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: Loopback1
    cidr: 10.224.112.2/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.122.2/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/1
    cidr: 10.224.12.4/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore1
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/2
    cidr: 10.224.12.6/31
    host_ip_index: 0
    vrf: CORE
    description: mckcore2
    enabled: true
    underlay: false
    physical: true
    ospf_active: true
    ospf_process: '1'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: true
    bgp_route_reflect: no
    
  - name: GigabitEthernet0/3
    cidr: 10.224.253.6/31
    host_ip_index: 0
    vrf: EDGE
    description: ashwan3
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.6/31
    host_ip_index: 0
    vrf: CORE
    description: ashwan3
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/3
    tunnel_destination: 10.224.253.7

  # -------
  # ashwan4
  # -------
  ashwan4:
  - name: Loopback1
    cidr: 10.224.113.4/32
    host_ip_index: 0
    vrf: CORE
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '1'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Loopback2
    cidr: 10.224.123.4/32
    host_ip_index: 0
    vrf: TRUSTED
    description: main_loopback
    enabled: true
    underlay: false
    physical: false
    ospf_active: true
    ospf_process: '2'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no

  - name: GigabitEthernet0/3
    cidr: 10.224.253.2/31
    host_ip_index: 1
    vrf: EDGE
    description: alnwan2
    enabled: true
    underlay: true
    physical: true
    ospf_active: false
    ospf_process: '0'
    bgp: false
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: false
    bgp_next_hop_self: false
    bgp_route_reflect: no
    
  - name: Tunnel1
    cidr: 10.224.254.2/31
    host_ip_index: 1
    vrf: CORE
    description: alnwan2
    enabled: true
    underlay: false
    physical: false
    ospf_active: false
    ospf_process: '0'
    bgp: true
    bgp_local_as: "{{ bgp.local_as }}"
    bgp_enabled: true
    bgp_next_hop_self: false
    bgp_route_reflect: no
    tunnel_source: GigabitEthernet0/3
    tunnel_destination: 10.224.253.3

# -----------------------------
# Route Redistribution Into BGP
# -----------------------------
redistribution:
  into_bgp:
    from_connected:
      route_map_entries:
      - vrf: CORE
        name: CONN_BGP_CORE
        sequence: 1000
        action: permit
        match_interfaces:
        - Loopback1

      - vrf: TRUSTED
        name: CONN_BGP_TRUSTED
        sequence: 1000
        action: permit
        match_interfaces: 
        - Loopback2