---
# -------------------------------------------------------------------
# Play - Basic Info such as Hostname, Domain, SNMP, logging, NTP info
# -------------------------------------------------------------------
- name: Configure Device Basic Information
  hosts: aln
  gather_facts: no
  tasks:
  # ----------------------------------------------------------
  # Updates Hostname, Domain-Name, DNS Lookup, and DNS servers
  # ----------------------------------------------------------
  - name: Configure Hostname / Domain-name
    cisco.ios.ios_system:
      hostname: "{{ inventory_hostname }}"
      domain_name: "{{ domain_name }}"
      lookup_enabled: no
      name_servers: "{{ dns_servers }}"
    tags:
    - basic
    - dns
    notify: save_cfg

  - name: Get Running Config
    cisco.ios.ios_command:
      commands:
      - sh run
    register: running_config
    tags:
    - basic
    - dns
  
  - name: Get Current List if DNS Servers
    set_fact: dns_servers_in_cfg="{{ 
      running_config.stdout[0] |
      regex_findall('^ip name-server (\S+)', multiline=True) }}"
    tags:
    - basic
    - dns
  
  - name: Remove Old DNS Servers
    cisco.ios.ios_config:
      lines:
      - "no ip name-server {{ item }}"
    when: item not in dns_servers
    loop: "{{ dns_servers_in_cfg }}"
    tags:
    - basic
    - dns
    notify: save_cfg
  
  # ---------------------------------------------------------------------------
  # Adds the desired NTP server to the configuration and also removes undesired
  # ---------------------------------------------------------------------------
  - name: Configure NTP
    cisco.ios.ios_ntp:
      server: "{{ ntp_server }}"
      logging: true
      state: present
      key_id: "10"
      auth_key: 15435A030726242723273C21181319000A
      auth: true
    tags:
    - basic
    - ntp
    notify: save_cfg
  
  - name: Get Running Config
    cisco.ios.ios_command:
      commands:
      - sh run
    register: running_config
    tags:
    - basic
    - ntp
  
  - name: Get Current List if NTP Servers
    set_fact: ntp_servers_in_cfg="{{
      running_config.stdout[0] |
      regex_findall('^ntp server (\S+)', multiline=True) }}"
    tags:
    - basic
    - ntp
  
  - name: Remove Old NTP Servers
    cisco.ios.ios_config:
      lines:
      - "no ntp server {{ item }}"
    when: item != ntp_server
    loop: "{{ ntp_servers_in_cfg }}"
    tags:
    - basic
    - ntp
    notify: save_cfg

  handlers:
  - name: save_cfg
    ios_command:
      commands:
      - write mem
    when: not ansible_check_mode

# -----------------------
# Configure L3 Interfaces
# -----------------------
- name: Change Switchports to Routed Ports Before Configuring L3 Interfaces
  hosts: aln_core
  gather_facts: no
  tasks:
  - name: Execute No Switchport Command on Switch Ports
    cisco.ios.ios_config:
      lines:
      - no switchport
      parents: "interface {{ item.name }}"
    loop: "{{ l3_interfaces[inventory_hostname] }}"
    tags:
    - switchports
    notify: save_cfg

  handlers:
  - name: save_cfg
    ios_command:
      commands:
      - write mem
    when: not ansible_check_mode

- name: Configure Device Interfaces
  hosts: aln
  gather_facts: no
  tasks:
  - name: Configure Underlay Interfaces with Lower MTU
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ item.name }}"
        mtu: "{{ underlay_mtu }}"
        description: "{{ item.description }}"
      state: merged
    tags:
    - interfaces
    - underlay
    loop: "{{ 
      l3_interfaces[inventory_hostname] |
      selectattr('underlay', 'equalto', 'yes') |
      list }}"
    notify: save_cfg

  - name: Configure Physical Interfaces
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ item.name }}"
        mtu: "{{ phys_intf_mtu }}"
        description: "{{ item.description }}"
      state: merged
    tags:
    - interfaces
    - physical
    loop: "{{ 
      l3_interfaces[inventory_hostname] |
      selectattr('underlay', 'equal', 'no') |
      list }}"
    notify: save_cfg

  - name: Configure Tunnel Interfaces
    cisco.ios.ios_interfaces:
      config:
      - name: "{{ item.name }}"
        description: "{{ item.description }}"
      state: merged
    tags:
    - interfaces
    - tunnel
    loop: "{{
      l3_interfaces[inventory_hostname] |
      selectattr('name', 'search', 'Tunnel') |
      list }}"
    notify: save_cfg


  - name: Create VRFs and Associate to Interfaces
    cisco.ios.ios_vrf:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      rd: "{{ item.rd }}"
      route_both: "{{ item.route_both }}"
      interfaces: "{{
        l3_interfaces[inventory_hostname] |
        selectattr('vrf', 'equalto', item.name ) |
        map(attribute='name') |
        list }}"
    loop: "{{ vrfs }}"
    tags:
    - interface
    - vrf
    notify: save_cfg

  - name: Assign IPv4 Address to Interfaces
    cisco.ios.ios_l3_interfaces:
      config: 
      - name: "{{ item.name }}"
        ipv4:
        - address: "{{ item.cidr | ipv4(item.host_ip_index) }}" 
    loop: "{{ l3_interfaces[inventory_hostname] }}"
    tags:
    - ip_address
    - interface
    notify: save_cfg

  - name: Interface Admin State
    cisco.ios.ios_interface:
      config:
      - enabled: "{{ item.enabled }}"
    loop: "{{ l3_interfaces[inventory_hostname] }}"
    notify: save_cfg

  handlers:
  - name: save_cfg
    ios_command:
      commands:
      - write mem
    when: not ansible_check_mode